let cars=[];let activeCategory='Wszystkie';const fmt=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const $=s=>document.querySelector(s);const grid=$('#carGrid'),search=$('#searchInput'),brand=$('#brandFilter'),sort=$('#sortSelect'),chips=$('#categoryChips'),empty=$('#emptyState'),count=$('#resultCount'),modal=$('#carModal');

function renderChips(){const cats=['Wszystkie',...new Set(cars.map(c=>c.category))];chips.innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');chips.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderChips();render();});}
function fillBrands(){[...new Set(cars.map(c=>c.brand))].sort().forEach(b=>brand.insertAdjacentHTML('beforeend',`<option value="${b}">${b}</option>`));}
function visible(){let q=search.value.trim().toLowerCase(),arr=cars.filter(c=>(activeCategory==='Wszystkie'||c.category===activeCategory)&&(!brand.value||c.brand===brand.value)&&(!q||`${c.name} ${c.brand} ${c.id} ${c.code}`.toLowerCase().includes(q)));if(sort.value==='priceAsc')arr.sort((a,b)=>a.price-b.price);else if(sort.value==='priceDesc')arr.sort((a,b)=>b.price-a.price);else if(sort.value==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));else arr.sort((a,b)=>(b.featured-a.featured)||a.id.localeCompare(b.id));return arr;}
function card(c){return `<article class="card" data-id="${c.id}" tabindex="0"><div class="card-img"><img loading="lazy" src="${c.image}" alt="${c.name}"><span class="badge">${c.category}</span></div><div class="card-body"><div class="card-top"><span>${c.brand}</span><span>${c.id}</span></div><h3>${c.name}</h3><div class="card-bottom"><span class="price">${fmt(c.price)}</span><span class="view">Zobacz auto →</span></div></div></article>`}
function render(){const arr=visible();grid.innerHTML=arr.map(card).join('');count.textContent=`${arr.length} z ${cars.length} pojazdów`;empty.hidden=arr.length>0;grid.querySelectorAll('.card').forEach(el=>{const open=()=>openModal(cars.find(c=>c.id===el.dataset.id));el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter')open();};});}
function openModal(c){$('#modalImage').src=c.image;$('#modalImage').alt=c.name;$('#modalCategory').textContent=c.category;$('#modalId').textContent=c.id;$('#modalName').textContent=c.name;$('#modalBrand').textContent=c.brand;$('#modalPrice').textContent=fmt(c.price);$('#modalVariants').textContent=c.variants;$('#modalCode').textContent=c.code;modal.showModal();}
$('#modalClose').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});search.oninput=render;brand.onchange=render;sort.onchange=render;
fetch('cars.json').then(r=>r.json()).then(data=>{cars=data;$('#vehicleCount').textContent=cars.length;fillBrands();renderChips();render();const f=cars.filter(x=>x.featured)[Math.floor(Math.random()*cars.filter(x=>x.featured).length)];$('#heroImage').src=f.image;$('#heroName').textContent=f.name;$('#heroCategory').textContent=f.category.toUpperCase();$('#heroPrice').textContent=fmt(f.price);}).catch(()=>{grid.innerHTML='<p>Nie udało się załadować katalogu. Uruchom stronę przez hosting lub prosty serwer lokalny.</p>';});